FROM debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        libsqlite3-0 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY server-bin /app/server
COPY config /app/config
RUN mkdir -p /app/data
EXPOSE 8080
ENV APP__SERVER__HOST=0.0.0.0
CMD ["/app/server"]
