name: On Deploy

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tag=${{ inputs.image-tag }}"
